package guide

import (
	"fmt"
	"io/fs"
	"strings"

	"github.com/dcsg/archway/internal/config"
)

// GenerateOptions holds the inputs for guide generation.
type GenerateOptions struct {
	ProjectDir   string
	Target       string
	Architecture string
	Capabilities []string
	Components   []config.Component
	TemplateFS   fs.FS // optional: embedded FS for pattern extraction
}

// Generate produces guide files for the specified target(s).
func Generate(opts GenerateOptions) error {
	content := buildContent(opts)

	targets, err := resolveTargets(opts.Target)
	if err != nil {
		return err
	}

	for _, t := range targets {
		if err := t.Write(opts.ProjectDir, content); err != nil {
			return fmt.Errorf("write guide for %s: %w", t.Name(), err)
		}
	}
	return nil
}

// GenerateFromConfig reads an ArchwayConfig and generates guides.
// An optional fs.FS can be passed to enable template pattern extraction.
func GenerateFromConfig(projectDir string, cfg *config.ArchwayConfig, target string, templateFS ...fs.FS) error {
	opts := GenerateOptions{
		ProjectDir:   projectDir,
		Target:       target,
		Architecture: cfg.Architecture,
		Capabilities: cfg.Capabilities,
		Components:   cfg.Components,
	}
	if len(templateFS) > 0 {
		opts.TemplateFS = templateFS[0]
	}
	return Generate(opts)
}

// buildContent generates the full markdown guide content.
func buildContent(opts GenerateOptions) string {
	var b strings.Builder

	writeHeader(&b)
	writeArchitecture(&b, opts.Architecture)
	writeLayerRules(&b, opts.Architecture, opts.Components)
	writeDependencyDirection(&b, opts.Architecture, opts.Components)
	writeAddingCode(&b, opts.Architecture)
	writeCapabilities(&b, opts.Capabilities)
	if patterns := ExtractPatterns(opts.TemplateFS, opts.Capabilities); patterns != "" {
		b.WriteString(patterns)
	}
	if catalog, err := BuildCatalog(opts.TemplateFS, opts.Capabilities); err == nil && len(catalog) > 0 {
		writeCatalog(&b, catalog, opts.Capabilities)
	}
	writeWarnings(&b, opts.Capabilities)
	writeSuggestions(&b, opts.Capabilities)
	writeAntiPatterns(&b, opts.Architecture)

	return b.String()
}

func writeHeader(b *strings.Builder) {
	b.WriteString("# Archway -- Architecture Guide\n\n")
	b.WriteString("> Auto-generated by `archway guide`. Do not edit manually.\n")
	b.WriteString("> Re-run `archway guide` to update.\n\n")
}

func writeArchitecture(b *strings.Builder, arch string) {
	b.WriteString("## Architecture: " + arch + "\n\n")
	switch arch {
	case "hexagonal":
		b.WriteString("This project uses hexagonal (ports & adapters) architecture.\n")
		b.WriteString("Business logic lives in the center (domain + service layers),\n")
		b.WriteString("isolated from infrastructure by ports (interfaces) and adapters (implementations).\n\n")
	case "layered":
		b.WriteString("This project uses layered architecture.\n")
		b.WriteString("Code is organized into four layers: handler, service, repository, and model.\n")
		b.WriteString("Dependencies flow strictly downward: handler → service → repository → model.\n\n")
	case "clean":
		b.WriteString("This project uses Clean Architecture (Uncle Bob).\n")
		b.WriteString("Code is organized into four layers: entity, usecase, interface, and infrastructure.\n")
		b.WriteString("Dependencies point inward: infrastructure → interface → usecase → entity.\n")
		b.WriteString("The entity layer has no external dependencies — it is the innermost ring.\n\n")
	case "flat":
		b.WriteString("This project uses a flat architecture.\n")
		b.WriteString("All code lives in a single package with no layer restrictions.\n\n")
	default:
		b.WriteString("Architecture type: " + arch + "\n\n")
	}
}

func writeLayerRules(b *strings.Builder, arch string, components []config.Component) {
	b.WriteString("## Layer Rules\n\n")

	if arch == "flat" {
		b.WriteString("No layer restrictions. All code lives in the root package.\n\n")
		return
	}

	if len(components) == 0 {
		return
	}

	for _, c := range components {
		b.WriteString("### " + c.Name + "\n")
		b.WriteString("- Directories: " + strings.Join(c.In, ", ") + "\n")
		if len(c.MayDependOn) == 0 {
			b.WriteString("- Dependencies: none (innermost layer)\n")
		} else {
			b.WriteString("- May depend on: " + strings.Join(c.MayDependOn, ", ") + "\n")
		}
		b.WriteString("\n")
	}
}

func writeDependencyDirection(b *strings.Builder, arch string, components []config.Component) {
	b.WriteString("## Dependency Direction\n\n")

	if arch == "flat" {
		b.WriteString("No dependency restrictions in flat architecture.\n\n")
		return
	}

	b.WriteString("Dependencies point **inward** toward the domain.\n\n")
	b.WriteString("**NEVER rules:**\n\n")

	for _, c := range components {
		forbidden := forbiddenDeps(c, components)
		for _, f := range forbidden {
			fmt.Fprintf(b, "- `%s` NEVER imports from `%s`\n", c.Name, f)
		}
	}
	b.WriteString("\n")
}

// forbiddenDeps returns component names that c must NOT depend on.
func forbiddenDeps(c config.Component, all []config.Component) []string {
	allowed := map[string]bool{c.Name: true}
	for _, dep := range c.MayDependOn {
		allowed[dep] = true
	}

	var forbidden []string
	for _, other := range all {
		if !allowed[other.Name] {
			forbidden = append(forbidden, other.Name)
		}
	}
	return forbidden
}

func writeAddingCode(b *strings.Builder, arch string) {
	b.WriteString("## Adding Code\n\n")

	if arch == "flat" {
		b.WriteString("Add new files to the root package. No special placement rules.\n\n")
		return
	}

	if arch == "clean" {
		b.WriteString("### New entity (enterprise business rule)\n")
		b.WriteString("1. Add to `internal/entity/`\n")
		b.WriteString("2. Entity MUST NOT import from usecase, interface, or infrastructure\n\n")

		b.WriteString("### New use case (application business rule)\n")
		b.WriteString("1. Add to `internal/usecase/`\n")
		b.WriteString("2. Use case may only import from `internal/entity/`\n")
		b.WriteString("3. Use case MUST NOT import from infrastructure\n\n")

		b.WriteString("### New interface adapter (handler, presenter, gateway)\n")
		b.WriteString("1. Add to `internal/interface/`\n")
		b.WriteString("2. Interface adapters may import from `internal/usecase/` and `internal/entity/`\n\n")

		b.WriteString("### New HTTP endpoint\n")
		b.WriteString("1. Add handler function in `internal/interface/handler/`\n")
		b.WriteString("2. Register route in `internal/interface/handler/router.go`\n")
		b.WriteString("3. Handler calls a use case; NEVER calls entity or infrastructure directly\n\n")

		b.WriteString("### New infrastructure component (DB, web, config)\n")
		b.WriteString("1. Add to `internal/infrastructure/`\n")
		b.WriteString("2. Infrastructure may import from all inner layers\n\n")
		return
	}

	if arch == "layered" {
		b.WriteString("### New model (shared entity)\n")
		b.WriteString("1. Add to `internal/model/`\n")
		b.WriteString("2. Model MUST NOT import from handler, service, or repository\n\n")

		b.WriteString("### New repository\n")
		b.WriteString("1. Add to `internal/repository/`\n")
		b.WriteString("2. Repository may only import from `internal/model/`\n\n")

		b.WriteString("### New service\n")
		b.WriteString("1. Add to `internal/service/`\n")
		b.WriteString("2. Service may import from `internal/repository/` and `internal/model/`\n\n")

		b.WriteString("### New HTTP endpoint\n")
		b.WriteString("1. Add handler function in `internal/handler/`\n")
		b.WriteString("2. Register route in `internal/handler/router.go`\n")
		b.WriteString("3. Handler calls service; NEVER calls repository directly\n\n")
		return
	}

	b.WriteString("### New domain entity\n")
	b.WriteString("1. Create the entity in `domain/`\n")
	b.WriteString("2. Define value objects and domain errors alongside it\n")
	b.WriteString("3. Domain MUST NOT import from any other layer\n\n")

	b.WriteString("### New port (interface)\n")
	b.WriteString("1. Define the interface in `port/`\n")
	b.WriteString("2. Ports may only import from `domain/`\n\n")

	b.WriteString("### New adapter (implementation)\n")
	b.WriteString("1. Create in `adapter/<type>/` (e.g., `adapter/httphandler/`, `adapter/mysqlrepo/`)\n")
	b.WriteString("2. Implement a port interface\n")
	b.WriteString("3. Adapters may import from `port/` and `domain/` only\n\n")

	b.WriteString("### New service / use case\n")
	b.WriteString("1. Add to `service/`\n")
	b.WriteString("2. Depend on ports (interfaces), not adapters (implementations)\n")
	b.WriteString("3. Services may import from `domain/` and `port/`\n\n")

	b.WriteString("### New HTTP endpoint\n")
	b.WriteString("1. Add handler function in `adapter/httphandler/`\n")
	b.WriteString("2. Register route in the router\n")
	b.WriteString("3. Handler calls a service via its port interface\n\n")
}

func writeCapabilities(b *strings.Builder, capabilities []string) {
	b.WriteString("## Capabilities\n\n")

	if len(capabilities) == 0 {
		b.WriteString("No capabilities configured.\n\n")
		return
	}

	b.WriteString("Installed capabilities:\n\n")
	for _, cap := range capabilities {
		dir := capabilityDir(cap)
		fmt.Fprintf(b, "- **%s** -- %s\n", cap, dir)
	}
	b.WriteString("\n")
}

// capabilityDir returns the typical directory for a capability.
func capabilityDir(cap string) string {
	dirs := map[string]string{
		"http-api":      "adapter/httphandler/",
		"grpc":          "adapter/grpchandler/, proto/",
		"graphql":       "adapter/graphql/",
		"sse":           "adapter/httphandler/",
		"mysql":         "adapter/mysqlrepo/",
		"postgres":      "adapter/postgresrepo/",
		"redis":         "adapter/redisrepo/",
		"mongodb":       "adapter/mongorepo/",
		"sqlite":        "adapter/sqliterepo/",
		"kafka":         "adapter/kafkahandler/",
		"s3":            "adapter/s3client/",
		"dynamodb":      "adapter/dynamorepo/",
		"observability": "platform/observability/",
		"config":        "config/",
		"docker":        "Dockerfile, docker-compose.yml",
		"ci-github":     ".github/workflows/",
		"makefile":      "Makefile",
		"saga":          "service/saga/",
		"feature-flags": "platform/featureflags/",
		"multi-tenancy": "adapter/httphandler/middleware/",
		"ci-gitlab":     ".gitlab-ci.yml",
		"devcontainer":  ".devcontainer/",
		"templ":         "adapter/httphandler/views/",
		"htmx":          "adapter/httphandler/",
		"static-assets": "static/",
	}
	if d, ok := dirs[cap]; ok {
		return d
	}
	return "see project structure"
}

func writeAntiPatterns(b *strings.Builder, arch string) {
	b.WriteString("## Anti-patterns to Avoid\n\n")

	// Common anti-patterns.
	b.WriteString("- NEVER create `utils/`, `helpers/`, `common/`, or `shared/` packages\n")
	b.WriteString("- NEVER use init() for business logic\n")
	b.WriteString("- NEVER ignore errors with `_`\n")

	if arch == "hexagonal" {
		b.WriteString("- NEVER import infrastructure packages from `domain/`\n")
		b.WriteString("- NEVER put business logic in HTTP handlers or adapters\n")
		b.WriteString("- NEVER depend on concrete implementations; use port interfaces\n")
		b.WriteString("- NEVER let domain types reference database/transport concerns (SQL tags, JSON tags in domain)\n")
		b.WriteString("- NEVER bypass the service layer; handlers must not call repositories directly\n")
	}

	if arch == "clean" {
		b.WriteString("- NEVER let `internal/entity/` import from usecase, interface, or infrastructure\n")
		b.WriteString("- NEVER let `internal/usecase/` import from infrastructure\n")
		b.WriteString("- NEVER put business logic in `internal/interface/` adapters; that is transport only\n")
		b.WriteString("- NEVER bypass use cases; interface adapters must not call entity methods directly for business operations\n")
		b.WriteString("- NEVER let infrastructure concerns (SQL tags, HTTP headers) leak into entities or use cases\n")
	}

	if arch == "layered" {
		b.WriteString("- NEVER put business logic in `internal/handler/`; that is transport only\n")
		b.WriteString("- NEVER import `internal/handler/` or `internal/service/` from `internal/repository/`\n")
		b.WriteString("- NEVER import `internal/handler/` or `internal/repository/` from each other directly\n")
		b.WriteString("- NEVER let handler bypass service and call repository directly\n")
		b.WriteString("- NEVER put data access (SQL, HTTP clients) in `internal/service/`\n")
	}

	b.WriteString("\n")
}
